input: ["i1", "i2"]
output: ["o1", "o2"]

# Eval related
batch_size: 32
data: data/coco.yaml
name: exp
save_dir: runs/val/
task: val
# weights: weights/yolov6n.pt
weights: weights/yolov6n-dict.pt

img_size: 640
conf_thres: 0.001
iou_thres: 0.65

device: "0"
half: false
